name: ModelEngineSignSpawner
main: com.elmakers.mine.bukkit.plugins.ModelEngineSignSpawner
version: 1.0
api-version: 1.17
author: NathanWolf, Ubuntuomega
description: Plugin para hacer carteles con modelos 3D
depend: [ModelEngine]
commands:
  spawnsign:
    description: Spawn a armorstand with a model attached
    usage: /spawnmodel <model>
    permission: ModelEngineSpawner.commands.spawnmodel
permissions:
  "ModelEngineSignSpawner.commands.spawnsign":
    description: A player may use the spawnmodel command
    default: op
  "ModelEngineSignSpawner.destroy":
    description: A player can destroy a 3D Sign
    default: op
