name: ModelEngineSpawner
main: com.elmakers.mine.bukkit.plugins.ModelEngineSpawner
version: 1.0
api-version: 1.16
author: NathanWolf
description: A plugin to test ModelEngine models
depend: [ModelEngine]
commands:
  spawnmodel:
    description: Spawn a mob with a model attached
    usage: /spawnmodel <model> [mob]
    permission: ModelEngineSpawner.commands.spawnmodel
permissions:
  "ModelEngineSpawner.commands.spawnmodel":
    description: A player may use the spawnmodel command
    default: op
